version: '3'
services:
    zabbix-appliance:
        image: "zabbix/zabbix-appliance:centos-4.0.2"
        environment:
            - TZ=Asia/Shanghai
            - PHP_TZ="Asia/Shanghai"
        ports:
            - "80:80"
            - "10051:10051"
            - "443:443"
        volumes:
            - "./var/log/mariadb:/var/log/mariadb"
            - "./var/lib/mysql:/var/lib/mysql"
    
    zabbix-agent:
        image: "zabbix/zabbix-agent:centos-4.0.2"
        environment:
            - TZ=Asia/Shanghai
            - PHP_TZ="Asia/Shanghai"
            - ZBX_SERVER_HOST=zabbix-appliance
        ports:
            - "10050:10050"
              #        volumes:
              #            - "./www:/usr/share/nginx/html"
