version: '3'
services:
    nginx:
        #image: "nginx:1.15"
        build: "nginx"
        environment:
            - TZ=Asia/Shanghai
        ports:
            - "80:80"
        volumes:
            - "./www:/usr/share/nginx/html"
            - "./nginx/etc:/etc/nginx"
            - "./nginx/var/log/nginx:/var/log/nginx"
              #            - "./nginx_etc:/etc/nginx:ro"
#        command: [nginx-debug, '-g', 'daemon off;'

    mysql:
        build: "mysql"
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=amz_admin!123
        ports:
            - "3306:3306"
        volumes:
            - "./mysql/var/lib/mysql:/var/lib/mysql"
            - "./mysql/etc:/etc/mysql/conf.d"
            - "./mysql/var/log/mysql:/var/log/mysql"
            - "./mysql/backup:/backup"

    php_fpm:
        build: "php_fpm"
        environment:
            - TZ=Asia/Shanghai
        ports:
            - "9000:9000"
        volumes:
            - "./www:/var/www/html"
            - "./php_fpm/etc/php.ini:/usr/local/etc/php/php.ini"
        #command: bash -c "usermod -u 1000 www-data && usermod -u 33 www-data"
